version: "3.7"

services:
  traefik:
    image: traefik
    container_name: demyx_traefik
    restart: unless-stopped
    command: 
      - --api
      - --api.statistics.recenterrors=100
      - --docker
      - --docker.watch=true
      - --docker.exposedbydefault=false
      - "--entrypoints=Name:http Address::80"
      #- "--entrypoints=Name:https Address::443 TLS"
      - --defaultentrypoints=http
      #- --defaultentrypoints=http,https
      #- --acme
      #- --acme.email=info@domain.tld
      #- --acme.storage=/etc/traefik/acme.json
      #- --acme.entrypoint=https
      #- --acme.onhostrule=true
      #- --acme.httpchallenge.entrypoint=http
      - --logLevel=INFO
      - --accessLog.filePath=/etc/traefik/access.log
      - --traefikLog.filePath=/etc/traefik/traefik.log
    networks:
      - demyx
    ports:
      - 80:80
      #- 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./acme.json:/etc/traefik/acme.json # chmod 600
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.domain.tld"
      #- "traefik.frontend.redirect.entryPoint=https"
      #- "traefik.frontend.auth.basic.users=${DEMYX_STACK_AUTH}"
      #- "traefik.frontend.headers.forceSTSHeader=true"
      #- "traefik.frontend.headers.STSSeconds=315360000"
      #- "traefik.frontend.headers.STSIncludeSubdomains=true"
      #- "traefik.frontend.headers.STSPreload=true"  
  db:
    container_name: demyx_db
    image: demyx/mariadb
    restart: unless-stopped
    networks:
      - demyx
    volumes:
      - demyx_db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: demyx_db
      MARIADB_USERNAME: demyx_user
      MARIADB_PASSWORD: demyx_password
      MARIADB_ROOT_PASSWORD: demyx_root_password
  nginx:
    container_name: demyx_nginx
    image: demyx/nginx
    restart: unless-stopped
    networks:
      - demyx
    volumes:
      - demyx_wp:/var/www/html
    environment:
      WORDPRESS: "true"
      WORDPRESS_SERVICE: wp
      WORDPRESS_DOMAIN: domain.tld
      DEMYX_UPLOAD_LIMIT: 128M
      DEMYX_NGINX_CACHE: "off"
      DEMYX_RATE_LIMIT: "off"
      TZ: America/Los_Angeles
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:domain.tld"
      #- "traefik.frontend.redirect.entryPoint=https"
      #- "traefik.frontend.auth.basic.users=${DEMYX_STACK_AUTH}"
      #- "traefik.frontend.headers.forceSTSHeader=true"
      #- "traefik.frontend.headers.STSSeconds=315360000"
      #- "traefik.frontend.headers.STSIncludeSubdomains=true"
      #- "traefik.frontend.headers.STSPreload=true"
  wp:
    container_name: demyx_wp
    image: demyx/wordpress
    restart: unless-stopped
    networks:
      - demyx
    volumes:
      - demyx_wp:/var/www/html
    environment:
      WORDPRESS_DOMAIN: domain.tld
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: demyx_db
      WORDPRESS_DB_USER: demyx_user
      WORDPRESS_DB_PASSWORD: demyx_password
      DEMYX_UPLOAD_LIMIT: 128M
      DEMYX_PHP_MEMORY: 256M
      DEMYX_PHP_MAX_EXECUTION_TIME: 300
      DEMYX_PHP_OPCACHE: "on"
      TZ: America/Los_Angeles
volumes:
  demyx_wp:
    name: demyx_wp
  demyx_db:
    name: demyx_db
networks:
  demyx:
    name: demyx
    